# For development configuration on local
version: '3.4'
services:
  app-server:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - stackName=development
      - apiKey=development
    depends_on:
      - db-server
  db-server:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=db_password
      - MONGO_INITDB_ROOT_USERNAME=bastion
