# For development configuration on local
version: '3'
services:
  app-server:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_USER=bastion
      - DB_PASSWORD=db_password
      - DB_HOST=db-server
      - DB_PORT=27017
      - DB_NAME=db-server
    depends_on:
      - db-server
  db-server:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=db_password
      - MONGO_INITDB_ROOT_USERNAME=bastion
